### ISSUE TITLE
11A3A in isolation looks weird

### ISSUE THREAD

**Issue by Mercury13** [notofonts/zanabazar-square#10]
### Title 
11A3A in isolation (w/o cluster) looks weird

### Font 
NotoSansZanabazarSquare-Regular.ttf

### Where the font came from, and when
Site: this repo, both release and gh-pages
Date: 2023-10-19

### Font Version
2.006 release
2.006 beta

### OS name and version
W10 22H2

### Application name and version
Qt 6.1.3

### Issue
1. Write 11A3A in isolation
2. Should write either lone 11A3A or 11A3A over 25CC
3. Writes 25CC, then 11A3A

### Character data
U+11A3A Zanabazar square cluster-initial letter Ra

### Screenshot
![image](https://github.com/notofonts/zanabazar-square/assets/10164882/19389e6a-0cfe-4b06-a4d5-51f0c4abe210)

**Comment by simoncozens** [comment]
This is the shaping engine adding the dotted circle, not the font. Maybe file an issue Harfbuzz if you think the cluster model is incorrect? (I don't, I think it's fine.)

**Comment by Mercury13** [comment]
@simoncozens Qt NEVER adds dotted circle!
Firefox
![image](https://github.com/notofonts/zanabazar-square/assets/10164882/055d5355-da34-4609-b583-cceab735d822)

Edge
![image](https://github.com/notofonts/zanabazar-square/assets/10164882/71ac4442-c43b-420d-b3e7-fb0b59a16327)

**Comment by simoncozens** [comment]
Then Qt isn't shaping this script properly. The Microsoft and Harfbuzz shapers are doing the right thing here.

**Comment by Mercury13** [comment]
@simoncozens NOOOOO!
![image](https://github.com/notofonts/zanabazar-square/assets/10164882/46eb5c08-5fcd-4970-8000-a318b89b305c)
