### ISSUE TITLE
11A3A in isolation still looks weird

### ISSUE THREAD

**Issue by Mercury13** [notofonts/zanabazar-square#11]
### Title 
11A3A in isolation (w/o cluster) still looks weird

### Font
NotoSansZanabazarSquare-Regular.ttf

### Where the font came from, and when
Site: this repo, both release and gh-pages
Date: 2023-10-19

### Font Version
2.006 release
2.006 beta

### OS name and version
W10 22H2, probably all OS (browsers now use engines detached from OS except for a few special legacy fonts)

### Application name and version
Multiple apps

### Issue
1. Write 11A3A in isolation
2. Should write either lone 11A3A or 11A3A over 25CC
3. Writes 25CC, then 11A3A

### Character data
U+11A3A Zanabazar square cluster-initial letter Ra

### Screenshot
Qt 6.1.3
![276568398-19389e6a-0cfe-4b06-a4d5-51f0c4abe210](https://github.com/notofonts/zanabazar-square/assets/10164882/06e99064-8e64-4e7d-a2fd-65164bc294dc)

Firefox
![276580289-055d5355-da34-4609-b583-cceab735d822](https://github.com/notofonts/zanabazar-square/assets/10164882/468392fa-9b28-45d6-9cdf-3bbdd9658c10)

Edge
![276580444-71ac4442-c43b-420d-b3e7-fb0b59a16327](https://github.com/notofonts/zanabazar-square/assets/10164882/b6f45de1-2462-427e-b6bf-ca0c96777f56)

Harfbuzz (shrunk to 40%, file is 4 bytes long F0 91 A8 BA)
![image](https://github.com/notofonts/zanabazar-square/assets/10164882/b5c186ec-a87d-4ee0-8093-6692b927101e)

**Comment by simoncozens** [comment]
I explained to you already that this is *not a font issue*. Please don't open another bug about this here. Not cool.

**Comment by Mercury13** [comment]
@simoncozens I don’t understand!
Its type is Letter/other. So it should not be hung upon 25CC.
You asked for Harfbuzz → I tested in Harfbuzz. If Harfbuzz if your reference, and it does troubles, then…

**Comment by simoncozens** [comment]
It's not about the glyph category in GDEF; it's about the USE category. U+11A3A has Indic_Syllabic_Category =Consonant_Prefixed and a USE category of R (repha). A repha in isolation forms a broken cluster, and so you get a dotted circle. The RA should be positioned at normal head height, not above the dotted circle (see L2/15-337 p. 23), so this is what you get. It's not ideal, but it's not a bug in the font.

**Comment by Mercury13** [comment]
@simoncozens Well, are there ways to write it in isolation or somehow else, using e.g. invisible characters?

**Comment by simoncozens** [comment]
Well, your use case in Unicodia is quite different from normal uses. You are not exactly setting text, so text engines are going to do things that you don't want.

If you want to force a font to *not* go through the USE, you could probably trick Harfbuzz into thinking it's a different script:

```
$ shape master_ttf/NotoSansZanabazarSquare-Regular.ttf -u 11A3A
[uni25CC=0+600|initialRa_zanb=0+840]
$ shape master_ttf/NotoSansZanabazarSquare-Regular.ttf -u 11A3A --script=latn
[initialRa_zanb=0+840]
```

**Comment by Mercury13** [comment]
Thanks, I’ll probably invent some way to trick them :)
