### ISSUE TITLE
Browsers are unable to auto-line-height Zanabazar/Tibetan scripts; how to handle it manually?

### ISSUE THREAD

**Issue by davelab6** [notofonts/zanabazar-square#12]
@tomasdev posted [internally](http://b/197844070) (and was originally flagged elsewhere [internally](https://buganizer.corp.google.com/issues/197102257) too):

"Basically, when using scripts that allow characters to be taller, the browser is unable to properly calculate the space a line will take as using line-height: initial (or normal)

https://lingojam.com/GlitchTextGenerator generates text with a bunch of those characters (try putting two lines)

A proposed solution is to include some sort of font renderer and calculate it ourselves (i.e., by using HarfbuzzJS) -- Tracking separately, as we won't include such an effort for Noto launch

We need to define the expected behavior of scripts like Zanabazar (that can be written in a mix of horizontal/vertical) in order to file the appropriate bugs with each browser vendor.

Mainly, given the Zanabazar sentences we have at https://fonts-sandbox.corp.google.com/noto/specimen/Noto+Sans+Zanabazar+Square should the default line height of the browsers:

a) be calculated for the tallest line, and then applied subsequently to all lines in that script-font-paragraph, making all lines in the same paragraph consistently spaced between each other?

![even lines](https://github.com/notofonts/zanabazar-square/assets/261579/00b354fa-bb5b-4f38-b5bf-272f64400790)

b) or should only the line that needs extra vertical space have a different height than the rest of the paragraph? 

![per lines](https://github.com/notofonts/zanabazar-square/assets/261579/c08bafdc-c616-4a9f-8a6f-5e7ea06d09b7)
"
* * * 

I am not sure there's any issue with the font, but I expect that the Noto project might want to recommend how to handle this to text engines. I suspect the (a) even-height rendering is more desirable for typographers, but I suspect (b) per-line rendering is what is more likely to be implemented, although currently this is what I see on https://fonts.google.com/noto/specimen/Noto+Sans+Zanabazar+Square on macOS Chrome:

<img width="543" alt="clashing lines" src="https://github.com/notofonts/zanabazar-square/assets/261579/f2d9172a-0a36-46e1-a7c6-9afc0b3bfaf9">

So, (a) @simoncozens is there any issue with the font and (b) what do you recommend for @tomasdev :)

**Comment by simoncozens** [comment]
Tomas is correct: there is no issue with the font, but this script is a challenge for rendering engines as the desired output is for the line height to be computed independently per line.
