### ISSUE TITLE
Missing Zanabazar Square contextual variants in Sanskrit

### ISSUE THREAD

**Issue by dscorbett** [notofonts/zanabazar-square#4]
### Font
NotoSansZanabazarSquare-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/7a9a8dbf7c9193298a1b11ad2e9acf5e039fc530/phaseIII_only/unhinted/otf/NotoSansZanabazarSquare/NotoSansZanabazarSquare-Regular.otf
Date: 2020-05-11

### Font version
Version 2.001

### Issue
Contextual variants are not enabled in Sanskrit.

### Character data
𑨀𑨆𑨂𑨐𑨆𑨇𑨣𑨇
U+11A00 ZANABAZAR SQUARE LETTER A
U+11A06 ZANABAZAR SQUARE VOWEL SIGN O
U+11A02 ZANABAZAR SQUARE VOWEL SIGN UE
U+11A10 ZANABAZAR SQUARE LETTER CA
U+11A06 ZANABAZAR SQUARE VOWEL SIGN O
U+11A07 ZANABAZAR SQUARE VOWEL SIGN AI
U+11A23 ZANABAZAR SQUARE LETTER TSA
U+11A07 ZANABAZAR SQUARE VOWEL SIGN AI

### Screenshot
Sanskrit:
![𑨀𑨆𑨂𑨐𑨆𑨇𑨣𑨇](https://user-images.githubusercontent.com/1124347/81936667-9be5a780-95c0-11ea-870d-96482be23a89.png)
default:
![𑨀𑨆𑨂𑨐𑨆𑨇𑨣𑨇](https://user-images.githubusercontent.com/1124347/81936669-9be5a780-95c0-11ea-8b0d-b059ef83dc6c.png)

**Comment by SKing-2003** [comment]
This appears to be resolved.
