### ISSUE TITLE
U+11A3A ZANABAZAR SQUARE CLUSTER-INITIAL LETTER RA reorders

### ISSUE THREAD

**Issue by dscorbett** [notofonts/zanabazar-square#8]
### Font
NotoSansZanabazarSquare-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/zanabazar-square/releases/tag/NotoSansZanabazarSquare-v2.005
Date: 2022-10-12

### Font version
Version 2.005

### Issue
If a cluster begins with U+11A3A ZANABAZAR SQUARE CLUSTER-INITIAL LETTER RA, the consonants below U+11A3A are moved below the previous cluster.

This happens because U+11A3A has Indic_Syllabic_Category=Consonant_Prefixed, so USE reorders it. [I recommended a different property value to Unicode in 2018](https://www.unicode.org/review/pri389/feedback.html) but [the action item](https://www.unicode.org/L2/L2019/19008.htm#158-A106) has been unaddressed for years. It is therefore up to the font to work around this issue.

### Character data
𑨋𑨺𑨋
U+11A0B ZANABAZAR SQUARE LETTER KA
U+11A3A ZANABAZAR SQUARE CLUSTER-INITIAL LETTER RA
U+11A0B ZANABAZAR SQUARE LETTER KA

### Screenshot
![𑨋𑨺𑨋](https://user-images.githubusercontent.com/1124347/195446634-bb8be959-f676-4d92-a7ff-216f08b34f8c.png)

**Comment by dscorbett** [comment]
This bug still exists in version 2.006 for clusters with more consonants, as in <U+11A3A, U+11A0B, U+11A47, U+11A30, U+11A47, U+11A19>:
![𑨺𑨋𑩇𑨰𑩇𑨙](https://github.com/notofonts/zanabazar-square/assets/1124347/65b0265a-e21f-426f-abed-48d3df909ee6)

**Comment by simoncozens** [comment]
I've just added a fix which should make this work for stacks of up to five consonants; the deepest attested using Zanabazar Square is three consonants, so that should be enough. Of course we have Tibetan and Sanskrit as well with potentially deeper stacks, but you've got to stop somewhere.
